/* ============================================================
   FLOWERS ETC — SITE DATA
   This is the ONE file to edit when the shop owner gives feedback.
   Change shop info, categories, products, prices, and photos here.
   ============================================================ */

const SHOP = {
  name: "Flowers Etc.",
  tagline: "Fresh & silk flowers for celebrations, sympathy, weddings & everyday moments.",
  phone: "(903) 567-7045",
  phoneHref: "9035677045",            // digits only — used for tap-to-call and text links
  email: "cantontxflowersetc@gmail.com",
  address: "1200 S Trade Days Blvd, Ste 150",
  cityStateZip: "Canton, TX 75103",
  hours: [
    { days: "Monday – Friday", time: "8:00 AM – 5:00 PM" },
    { days: "Saturday",        time: "8:00 AM – 12:00 PM" },
    { days: "Sunday",          time: "Closed — funeral delivery may be available by arrangement" },
  ],
  // Shown on the home page — edit freely
  established: "",                    // optional year, e.g. "1998" — currently unused (site avoids dates)
  ownerName: "Lisa Thompson",
  deliveryArea: "Canton and nearby towns within 35 miles",
  deliveryTowns: ["Mabank", "Wills Point", "Van", "Grand Saline", "Martins Mill", "Ben Wheeler"],
  deliveryFees: {
    cantonCityLimits: 5,
    justOutsideCanton: 10,
    fartherWithin35Miles: 15,
  },
  sameDayCutoff: "2:30 PM Monday–Friday and 10:00 AM Saturday",
  holidayHoursNote: "Holiday availability varies — call the shop to confirm.",
  closedDayNote: "Sunday is closed; funeral delivery may be available by arrangement.",
  missedRecipientNote: "If no one answers, we'll try to contact the customer or recipient and leave the order safely when conditions allow. If it cannot be left safely, we'll contact you to arrange the next step.",
  facebook: "https://www.facebook.com/FlowersEtcofCanton/",
  facebookMessenger: "https://m.me/FlowersEtcofCanton",
  instagram: "",                      // same for Instagram

  deliveryPhotoNote: "Delivery or placement photos are available by request.",
  facilityNote: "Flowers Etc. does not add special facility restrictions. Hospitals, schools, care communities, funeral homes, and workplaces may have their own rules, so we confirm recipient and facility details before delivery.",
  funeralOrderNote: "Please place funeral orders at least 24 hours ahead. We plan to deliver at least one hour before the service. Depending on the design, size, and flower availability, we may be able to help on a shorter timeline—call to confirm.",

  // Announcement banner — shows at the very top of every page when not "".
  // Leave "" and the seasonal banners below will fill it in automatically.
  announcement: "",

  // Shown wherever we name specific flowers, so customers know
  // seasonal swaps can happen. Set to "" to hide it everywhere.
  substitutionNote:
    "Flowers and colors depend on the season and what is currently in the shop. " +
    "If a requested bloom isn't on hand, we may be able to source it when your pickup " +
    "or delivery date allows. Otherwise, we'll substitute a similar bloom of equal or " +
    "greater value while matching the style and color direction you chose. A member of " +
    "our team will confirm availability and call before making any significant change.",

  // Shown on every product — the "make it yours" invitation. Set "" to hide.
  customizeNote:
    "Don't see quite what you had in mind? Don't hesitate to give us a call — " +
    "we can customize this arrangement to be whatever you want it to be. " +
    "(Additional fees may apply depending on the changes.)",

  // Shown on every product — the ordering-notice heads-up. Set "" to hide.
  noticeNote:
    "We prefer at least 24 hours' notice on orders so we can make sure the " +
    "flowers you want are in stock. If something isn't available, we'll contact " +
    "you right away and work out the perfect substitute together.",
};

/* ------------------------------------------------------------
   CATEGORIES — id must match the "category" field on products.
   Add, remove, or rename freely; the shop page updates itself.
   ------------------------------------------------------------ */
const CATEGORIES = [
  {
    id: "sympathy",
    name: "Sympathy & funeral",
    blurb: "Casket sprays, easels, wreaths & hearts, service flowers, cemetery flowers, and keepsakes.",
  },
  {
    id: "everyday",
    name: "Everyday flowers",
    blurb: "Birthdays, anniversaries, get-well wishes, or no reason at all.",
  },
  {
    id: "gifts",
    name: "Plants & gifts",
    blurb: "Living plants, dish gardens, keepsakes, gift baskets, and stuffed animals.",
  },
  {
    id: "wedding",
    name: "Wedding, prom & personal flowers",
    blurb: "Bouquets, corsages, boutonnieres, and coordinated wedding design by consultation.",
  },
];

/* Sub-filters shown on the shop page when Sympathy & funeral is selected. */
const SYMPATHY_SUBCATS = [
  { id: "all", name: "All sympathy & funeral" },
  { id: "casket", name: "Casket sprays" },
  { id: "easels", name: "Easels" },
  { id: "wreath", name: "Wreaths & hearts" },
  { id: "service", name: "For the service" },
  { id: "cemetery", name: "Cemetery flowers" },
  { id: "keepsakes", name: "Plants & keepsakes" },
];

/* ------------------------------------------------------------
   PRODUCTS
   Each product needs:
     name      — display name
     category  — one of the category ids above
     price     — number, or a string like "From $85" / "$175 – $400+"
     desc      — one or two sentences
     image     — filename inside the /images folder ("" = elegant placeholder;
                 products without a photo automatically sort to the bottom)
     order     — "buy"    → shows a Buy Now button (uses buyLink)
                 "custom" → shows Call to Order (phone) + inquiry option
     buyLink   — future secure-payment URL (only for order: "buy";
                 leave "" until the payment account is set up — the button
                 will show "Call to Order" as a fallback automatically)

   Optional extras:
     flowers   — the actual flowers pictured, e.g. flowers: ["Roses", "Stock"]
     colors    — color choices, e.g. colors: ["Red & white", "You choose"]
     sizes     — price tiers, e.g. sizes: [{ label: "Dozen", price: 75 }, ...]
                 (when present, the card shows "From $<lowest>")
     photos    — extra photo filenames for the detail-page gallery
     galleryKind — "examples" for handmade style inspiration (default), or
                   "inventory" when photos show rotating keepsake inventory
     notice    — a product-specific ordering note shown prominently,
                 e.g. "Please allow at least 24 hours."
     salePrice — TEMPORARY promo price. Overrides everything and shows the
                 old price struck through. Delete the line to end the sale.
     saleNote  — small badge for the sale, e.g. "Mother's Day Special"
   ------------------------------------------------------------ */
const PRODUCTS = [
  // ——— Sympathy & funeral · Casket sprays (Lisa-confirmed work; drafts pending approval) ———
  {
    name: "Gentle Pink Garden",
    category: "sympathy",
    subcat: "casket",
    price: "From $425",  // DRAFT PRICE — Lisa approval required
    desc: "A full garden of pink, blush and white blooms with soft movement and traditional greenery.",
    image: "lisa-001.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Golden Grace",
    category: "sympathy",
    subcat: "casket",
    price: "From $395",  // DRAFT PRICE — Lisa approval required
    desc: "Yellow roses, lilies and mums gathered into a warm, light-filled tribute.",
    image: "lisa-002.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Blue Ribbon Remembrance",
    category: "sympathy",
    subcat: "casket",
    price: "From $425",  // DRAFT PRICE — Lisa approval required
    desc: "Blue and white flowers with ribbon detail for a calm, tailored farewell.",
    image: "lisa-007.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Celebration of Color",
    category: "sympathy",
    subcat: "casket",
    price: "From $475",  // DRAFT PRICE — Lisa approval required
    desc: "Sunflowers, lilies, roses and saturated garden color arranged to celebrate a vibrant life.",
    image: "lisa-010.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Blush Garden Tribute",
    category: "sympathy",
    subcat: "casket",
    price: "From $525",  // DRAFT PRICE — Lisa approval required
    desc: "An abundant pink tribute layered with roses, lilies, carnations and garden texture.",
    image: "lisa-014.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Red Rose Remembrance",
    category: "sympathy",
    subcat: "casket",
    price: "From $425",  // DRAFT PRICE — Lisa approval required
    desc: "Red and white roses with lilies and graceful greenery for a traditional expression of love.",
    image: "lisa-050.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Soft Blush Rose",
    category: "sympathy",
    subcat: "casket",
    price: "From $395",  // DRAFT PRICE — Lisa approval required
    desc: "Pale pink roses and baby's breath in a quiet, classic casket design.",
    image: "lisa-055.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Peaceful White Rose",
    category: "sympathy",
    subcat: "casket",
    price: "From $425",  // DRAFT PRICE — Lisa approval required
    desc: "White roses, lilies and snapdragons arranged with clean, dignified lines.",
    image: "lisa-056.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Golden Rose Farewell",
    category: "sympathy",
    subcat: "casket",
    price: "From $425",  // DRAFT PRICE — Lisa approval required
    desc: "Golden roses and lilies with fresh greenery and warm peach accents.",
    image: "lisa-059.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Autumn Warmth",
    category: "sympathy",
    subcat: "casket",
    price: "From $425",  // DRAFT PRICE — Lisa approval required
    desc: "Orange lilies, golden roses and fall-toned flowers in a generous seasonal tribute.",
    image: "lisa-061.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Rose Garden Farewell",
    category: "sympathy",
    subcat: "casket",
    price: "From $450",  // DRAFT PRICE — Lisa approval required
    desc: "Layered pink roses and airy greenery with a garden-grown feeling.",
    image: "lisa-066.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Red Rose & Blue Hydrangea",
    category: "sympathy",
    subcat: "casket",
    price: "From $450",  // DRAFT PRICE — Lisa approval required
    desc: "Red roses and blue hydrangea designed with patriotic color and rich texture.",
    image: "lisa-068.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Golden Meadow",
    category: "sympathy",
    subcat: "casket",
    price: "From $475",  // DRAFT PRICE — Lisa approval required
    desc: "A broad sweep of yellow roses, blue accents and airy white flowers.",
    image: "lisa-074.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "White Garden Grace",
    category: "sympathy",
    subcat: "casket",
    price: "From $475",  // DRAFT PRICE — Lisa approval required
    desc: "White roses, lilies and trailing greenery in an organic garden-style tribute.",
    image: "lisa-075.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Lavender Garden Farewell",
    category: "sympathy",
    subcat: "casket",
    price: "From $475",  // DRAFT PRICE — Lisa approval required
    desc: "Lavender, plum and blush flowers gathered into a full, expressive casket spray.",
    image: "lisa-076.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Texas Honor Casket Spray",
    category: "sympathy",
    subcat: "casket",
    price: "From $450",  // DRAFT PRICE — Lisa approval required
    desc: "Red roses, white lilies and blue accents with Texas flags for a personal service tribute.",
    image: "lisa-077.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Blue & White Peace",
    category: "sympathy",
    subcat: "casket",
    price: "From $425",  // DRAFT PRICE — Lisa approval required
    desc: "Blue hydrangea, white roses and lilies arranged in a serene, traditional palette.",
    image: "lisa-081.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Cowboy's Farewell",
    category: "sympathy",
    subcat: "casket",
    price: "From $450",  // DRAFT PRICE — Lisa approval required
    desc: "An all-white tribute designed around a treasured cowboy hat and the life it represents.",
    image: "lisa-083.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Bluebonnet Gold",
    category: "sympathy",
    subcat: "casket",
    price: "From $450",  // DRAFT PRICE — Lisa approval required
    desc: "Golden roses, blue delphinium and white accents with an unmistakably Texas spirit.",
    image: "lisa-089.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Woodland White",
    category: "sympathy",
    subcat: "casket",
    price: "From $475",  // DRAFT PRICE — Lisa approval required
    desc: "White roses and lilies with branches, trailing greenery and natural woodland movement.",
    image: "lisa-090.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  // ——— Sympathy & funeral · Easels ———
  {
    name: "Golden Light Easel",
    category: "sympathy",
    subcat: "easels",
    price: "From $225",  // DRAFT PRICE — Lisa approval required
    desc: "Yellow lilies, roses and mums arranged vertically for a warm service presentation.",
    image: "lisa-003.webp",
    designType: "Easel",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Beloved Grandmother Tribute",
    category: "sympathy",
    subcat: "easels",
    price: "From $275",  // DRAFT PRICE — Lisa approval required
    desc: "Pink roses and garden flowers with personalized ribbon detail. Two photographs show the same design.",
    image: "lisa-004.webp",
    photos: ["lisa-005.webp"],
    designType: "Easel",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Bright Memories Easel",
    category: "sympathy",
    subcat: "easels",
    price: "From $250",  // DRAFT PRICE — Lisa approval required
    desc: "Yellow, pink and lavender flowers arranged in a bright, uplifting tribute.",
    image: "lisa-006.webp",
    designType: "Easel",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Sunflower Spirit",
    category: "sympathy",
    subcat: "easels",
    price: "From $250",  // DRAFT PRICE — Lisa approval required
    desc: "Sunflowers and vivid garden flowers designed tall with a joyful sense of movement.",
    image: "lisa-011.webp",
    designType: "Easel",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Lavender Grace Easel",
    category: "sympathy",
    subcat: "easels",
    price: "From $250",  // DRAFT PRICE — Lisa approval required
    desc: "Lavender and blush flowers with delicate branches and soft cascading greenery.",
    image: "lisa-049.webp",
    designType: "Easel",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Cross of Color",
    category: "sympathy",
    subcat: "easels",
    price: "From $275",  // DRAFT PRICE — Lisa approval required
    desc: "A cross-shaped tribute filled with red, orange and yellow flowers.",
    image: "lisa-051.webp",
    designType: "Easel",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "White Cascade Easel",
    category: "sympathy",
    subcat: "easels",
    price: "From $275",  // DRAFT PRICE — Lisa approval required
    desc: "White lilies and roses with deep burgundy accents and a long, graceful silhouette.",
    image: "lisa-058.webp",
    designType: "Easel",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Texas Honor Easel",
    category: "sympathy",
    subcat: "easels",
    price: "From $250",  // DRAFT PRICE — Lisa approval required
    desc: "Red, white and blue flowers with ribbon detail for a patriotic remembrance.",
    image: "lisa-062.webp",
    designType: "Easel",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Blue & Gold Remembrance",
    category: "sympathy",
    subcat: "easels",
    price: "From $250",  // DRAFT PRICE — Lisa approval required
    desc: "Blue and golden flowers gathered into a tall, traditional service tribute.",
    image: "lisa-063.webp",
    designType: "Easel",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Patriotic Rose Easel",
    category: "sympathy",
    subcat: "easels",
    price: "From $275",  // DRAFT PRICE — Lisa approval required
    desc: "Red, white and blue roses with personalized ribbon and a full formal shape.",
    image: "lisa-067.webp",
    designType: "Easel",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Blue & Gold Easel",
    category: "sympathy",
    subcat: "easels",
    price: "From $250",  // DRAFT PRICE — Lisa approval required
    desc: "Yellow roses and blue flowers arranged with generous height and presence.",
    image: "lisa-071.webp",
    designType: "Easel",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Meadow Gold Sympathy Arrangement",
    category: "sympathy",
    subcat: "service",
    price: "From $250",  // DRAFT PRICE — Lisa approval required
    desc: "Golden roses, blue delphinium and airy white accents in a garden-inspired sympathy arrangement.",
    image: "lisa-073.webp",
    designType: "Funeral service arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Burgundy Grace Easel",
    category: "sympathy",
    subcat: "easels",
    price: "From $250",  // DRAFT PRICE — Lisa approval required
    desc: "Burgundy and white roses in a tall, tailored tribute with personal ribbon.",
    image: "lisa-078.webp",
    designType: "Easel",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Blue & White Easel",
    category: "sympathy",
    subcat: "easels",
    price: "From $250",  // DRAFT PRICE — Lisa approval required
    desc: "White flowers, blue accents and yellow roses in a balanced standing design.",
    image: "lisa-082.webp",
    designType: "Easel",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Sunflower Farewell",
    category: "sympathy",
    subcat: "easels",
    price: "From $225",  // DRAFT PRICE — Lisa approval required
    desc: "Sunflowers and greenery arranged tall for a warm, natural remembrance.",
    image: "lisa-084.webp",
    designType: "Easel",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  // ——— Sympathy & funeral · Wreaths & hearts ———
  {
    name: "Pink Garden Wreath",
    category: "sympathy",
    subcat: "wreath",
    price: "From $275",  // DRAFT PRICE — Lisa approval required
    desc: "Pink lilies, roses and garden flowers arranged in a full open circle.",
    image: "lisa-008.webp",
    designType: "Wreath, heart or shaped tribute",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Red & White Photo Wreath",
    category: "sympathy",
    subcat: "wreath",
    price: "From $295",  // DRAFT PRICE — Lisa approval required
    desc: "A red and white memorial wreath designed to frame a treasured photograph.",
    image: "lisa-009.webp",
    designType: "Wreath, heart or shaped tribute",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Blue & White Remembrance Wreath",
    category: "sympathy",
    subcat: "wreath",
    price: "From $250",  // DRAFT PRICE — Lisa approval required
    desc: "Blue and white flowers in a classic open wreath with ribbon detail.",
    image: "lisa-045.webp",
    designType: "Wreath, heart or shaped tribute",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Blush Remembrance Wreath",
    category: "sympathy",
    subcat: "wreath",
    price: "From $250",  // DRAFT PRICE — Lisa approval required
    desc: "Pink and white flowers gathered into a soft, traditional circle.",
    image: "lisa-046.webp",
    designType: "Wreath, heart or shaped tribute",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Rose Garden Wreath",
    category: "sympathy",
    subcat: "wreath",
    price: "From $295",  // DRAFT PRICE — Lisa approval required
    desc: "Pink lilies, roses and layered garden flowers in a romantic open wreath.",
    image: "lisa-048.webp",
    designType: "Wreath, heart or shaped tribute",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Rose & Ribbon Wreath",
    category: "sympathy",
    subcat: "wreath",
    price: "From $275",  // DRAFT PRICE — Lisa approval required
    desc: "Pink and purple roses with personalized ribbon in a graceful open design.",
    image: "lisa-057.webp",
    designType: "Wreath, heart or shaped tribute",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Heartfelt White",
    category: "sympathy",
    subcat: "wreath",
    price: "From $325",  // DRAFT PRICE — Lisa approval required
    desc: "A white floral heart accented with a soft spray of pink garden flowers.",
    image: "lisa-069.webp",
    designType: "Wreath, heart or shaped tribute",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Golden Rose Wreath",
    category: "sympathy",
    subcat: "wreath",
    price: "From $325",  // DRAFT PRICE — Lisa approval required
    desc: "Golden roses and blue ribbon arranged in a full heart-shaped tribute.",
    image: "lisa-072.webp",
    designType: "Wreath, heart or shaped tribute",
    coverageLabel: "Presentation",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  // ——— Sympathy & funeral · For the service ———
  {
    name: "Golden Tribute",
    category: "sympathy",
    subcat: "service",
    price: "From $225",  // DRAFT PRICE — Lisa approval required
    desc: "Golden roses and yellow garden flowers in a classic service presentation.",
    image: "lisa-047.webp",
    designType: "Funeral service arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Red Rose Service Arrangement",
    category: "sympathy",
    subcat: "service",
    price: "From $175",  // DRAFT PRICE — Lisa approval required
    desc: "A tall red rose arrangement for the service, designed in a traditional pedestal style.",
    image: "lisa-053.webp",
    designType: "Funeral service arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Lantern & Roses Tribute",
    category: "sympathy",
    subcat: "service",
    price: "From $165",  // DRAFT PRICE — Lisa approval required
    desc: "Red and white roses designed around a keepsake memorial lantern.",
    image: "lisa-054.webp",
    designType: "Funeral service arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Peaceful White Service Tribute",
    category: "sympathy",
    subcat: "service",
    price: "From $175",  // DRAFT PRICE — Lisa approval required
    desc: "White lilies and hydrangea with greenery in a low, graceful service arrangement.",
    image: "lisa-060.webp",
    designType: "Funeral service arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Rose Garden Service Arrangement",
    category: "sympathy",
    subcat: "service",
    price: "From $195",  // DRAFT PRICE — Lisa approval required
    desc: "Pink and red roses arranged with height for a heartfelt service presentation.",
    image: "lisa-065.webp",
    designType: "Funeral service arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "White Lily Service Arrangement",
    category: "sympathy",
    subcat: "service",
    price: "From $175",  // DRAFT PRICE — Lisa approval required
    desc: "White lilies with red accents in a tall, dignified floor arrangement.",
    image: "lisa-085.webp",
    designType: "Funeral service arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Garden Sympathy Basket",
    category: "sympathy",
    subcat: "service",
    price: "From $165",  // DRAFT PRICE — Lisa approval required
    desc: "Living greenery and garden flowers gathered into a full sympathy basket.",
    image: "lisa-086.webp",
    designType: "Funeral service arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Serene White Urn Tribute",
    category: "sympathy",
    subcat: "service",
    price: "From $400",
    desc: "A graceful all-white funeral tribute designed to surround and honor an urn with timeless elegance. Featuring soft white blooms and lush greenery, this arrangement creates a peaceful and comforting display for memorial services, celebrations of life, and funeral gatherings. Flower varieties may vary slightly based on seasonal availability while maintaining the overall look and feel.",
    image: "serene-white-urn-tribute.webp",
    designType: "Funeral urn tribute",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Orchid Urn Tribute",
    category: "sympathy",
    subcat: "service",
    price: "From $225",  // DRAFT PRICE — Lisa approval required
    desc: "An elegant all-white urn tribute designed with soft white blooms and fresh greenery to create a peaceful, refined memorial display. Flower varieties may vary based on seasonal availability while maintaining the overall white-and-green design.",
    image: "lisa-087.webp",
    designType: "Funeral service arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Ask about a smaller version", "Ask about a fuller version"],
    notice: SHOP.funeralOrderNote,
    draft: true,
    order: "buy",
    buyLink: "",
  },
  // ——— Sympathy & funeral · Cemetery flowers ———
  {
    name: "Custom Cemetery Flowers",
    category: "sympathy",
    subcat: "cemetery",
    price: 50,
    desc: "Custom silk cemetery flowers made in the flower types, colors, and style you request. We create different styles, including standard cemetery arrangements and headstone saddles. The photographs are examples and variations; tell us what you would like and our team will confirm the dimensions and available materials.",
    image: "lisa-023.webp",
    photos: ["lisa-024.webp", "lisa-026.webp", "lisa-042.webp", "blue-yellow-silk-cemetery.webp", "blue-yellow-silk-cemetery-2.webp", "silk-cemetery-arrangement.jpg", "cemetery-headstone-saddle.webp"],
    designType: "Custom cemetery flowers",
    coverageLabel: "Placement",
    coverageOptions: ["Cemetery vase arrangement — confirm dimensions"],
    notice: "A member of our team will confirm the cemetery, vase measurements, flower and color requests, and requested placement date before the schedule begins.",
    order: "buy",
    buyLink: "",
  },
  // ——— Everyday flowers ———
  {
    name: "Classic Rose Bouquet",
    category: "everyday",
    price: 85,
    sizes: [
      { label: "Half Dozen", price: 55 },
      { label: "Dozen",      price: 85 },
      { label: "Two Dozen",  price: 165 },
    ],
    orderOptions: {
      label: "Rose color",
      options: ["Red", "Pink", "Yellow", "White", "Special Request — 24 hours notice required"],
    },
    desc: "A classic rose bouquet with fresh greenery for a romantic, thoughtful, or sympathy message. Red, pink, yellow, and white roses are normally kept in stock. With at least 24 hours notice, other rose colors can be specially ordered.",
    image: "lisa-043.webp",
    photos: ["rose-bouquet-example-2.webp", "rose-bouquet-example-1.webp"],
    designType: "Fresh flower arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Soft Garden Basket",
    category: "everyday",
    price: "From $75",  // DRAFT PRICE — Lisa approval required
    desc: "Pink, white and lavender flowers in a soft garden-style basket for everyday sending or a gentle sympathy message.",
    image: "lisa-044.webp",
    designType: "Fresh flower basket",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Sunshine & Lilies",
    category: "everyday",
    price: "From $95",  // DRAFT PRICE — Lisa approval required
    desc: "Yellow roses and callas, pink lilies and green hydrangea in a bright glass vase.",
    image: "lisa-012.webp",
    designType: "Fresh flower arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Coral Rose Cube",
    category: "everyday",
    price: "From $65",  // DRAFT PRICE — Lisa approval required
    desc: "Coral and hot-pink roses with carnations in a modern glass cube.",
    image: "lisa-013.webp",
    designType: "Fresh flower arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Golden Morning",
    category: "everyday",
    price: "From $75",  // DRAFT PRICE — Lisa approval required
    desc: "Yellow roses and gladiolus gathered into a tall, cheerful vase.",
    image: "lisa-018.webp",
    designType: "Fresh flower arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Purple Birthday Basket",
    category: "everyday",
    price: "From $65",  // DRAFT PRICE — Lisa approval required
    desc: "Pink roses, purple flowers and green button mums finished with a bright bow.",
    image: "lisa-019.webp",
    designType: "Fresh flower arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Coral Gerbera Garden",
    category: "everyday",
    price: "From $85",  // DRAFT PRICE — Lisa approval required
    desc: "Coral roses and gerbera daisies with hydrangea and garden texture.",
    image: "lisa-021.webp",
    designType: "Fresh flower arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "White Rose Cloud",
    category: "everyday",
    price: "From $65",  // DRAFT PRICE — Lisa approval required
    desc: "White roses and hydrangea with baby's breath in a compact vase.",
    image: "lisa-022.webp",
    designType: "Fresh flower arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Pink Lily Garden",
    category: "everyday",
    price: "From $85",  // DRAFT PRICE — Lisa approval required
    desc: "Pink lilies, roses and snapdragons gathered into a tall glass vase.",
    image: "lisa-025.webp",
    designType: "Fresh flower arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Blush Rose Vase",
    category: "everyday",
    price: "From $95",  // DRAFT PRICE — Lisa approval required
    desc: "Blush roses, hydrangea and white flowers arranged with eucalyptus and fresh greenery.",
    image: "lisa-027.webp",
    designType: "Fresh flower arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Birthday Flowers & Balloons",
    category: "everyday",
    price: "From $75",  // DRAFT PRICE — Lisa approval required
    desc: "A bright mixed vase finished with a celebratory balloon cluster.",
    image: "lisa-028.webp",
    designType: "Fresh flower arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Blush Garden Bouquet",
    category: "wedding",
    price: "From $145",
    desc: "A romantic blush bouquet with lavender accents and branching greenery, designed by consultation for weddings and special events.",
    image: "lisa-029.webp",
    photos: ["blush-garden-bouquet-example.webp"],
    designType: "Wedding bouquet",
    coverageLabel: "Design request",
    coverageOptions: ["Use the photographed design as direction", "Coordinate with my wedding colors"],
    order: "custom",
    buyLink: "",
  },
  {
    name: "Jewel Garden Vase",
    category: "everyday",
    price: "From $95",  // DRAFT PRICE — Lisa approval required
    desc: "Purple lilies, hydrangea and jewel-toned flowers. Two photographs show the same design.",
    image: "lisa-034.webp",
    photos: ["lisa-035.webp"],
    designType: "Fresh flower arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Peach & Purple Garden",
    category: "everyday",
    price: "From $85",  // DRAFT PRICE — Lisa approval required
    desc: "Peach roses, purple flowers and cool blue accents in a tall garden arrangement.",
    image: "lisa-052.webp",
    designType: "Fresh flower arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Pink Rose Vase",
    category: "everyday",
    price: "From $55",  // DRAFT PRICE — Lisa approval required
    desc: "Pink roses and delicate accent flowers in a classic clear vase.",
    image: "lisa-070.webp",
    designType: "Fresh flower arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "White Lily Statement",
    category: "everyday",
    collections: ["everyday", "sympathy"],
    subcat: "service",
    price: "From $95",  // DRAFT PRICE — Lisa approval required
    desc: "White lilies, roses and branches in a tall, architectural vase design.",
    image: "lisa-091.webp",
    designType: "Fresh flower arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  // ——— Plants & gifts (cross-listed under Sympathy · Plants & keepsakes) ———
  {
    name: "Green Garden Basket",
    category: "gifts",
    collections: ["gifts", "sympathy"],
    subcat: "keepsakes",
    price: "From $60",  // DRAFT PRICE — Lisa approval required
    desc: "A mixed living plant basket prepared as a lasting gift.",
    image: "lisa-015.webp",
    designType: "Plant or keepsake",
    coverageLabel: "Selection",
    coverageOptions: ["As photographed or closest current option"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Peace Lily Plant",
    category: "gifts",
    collections: ["gifts", "sympathy"],
    subcat: "keepsakes",
    price: "From $45",  // DRAFT PRICE — Lisa approval required
    desc: "A classic peace lily finished with a bow; container style depends on availability.",
    image: "lisa-020.webp",
    designType: "Plant or keepsake",
    coverageLabel: "Selection",
    coverageOptions: ["As photographed or closest current option"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Standing Cross Keepsake",
    category: "gifts",
    collections: ["gifts", "sympathy"],
    subcat: "keepsakes",
    price: 50,
    desc: "A whitewashed standing cross with dark metal scrollwork.",
    image: "lisa-036.webp",
    designType: "Plant or keepsake",
    coverageLabel: "Selection",
    coverageOptions: ["As photographed or closest current option"],
    draftNote: "This item's price was previously confirmed. The listing name and details shown here are drafts awaiting Lisa's review.",
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Memorial Plaques",
    category: "gifts",
    collections: ["gifts", "sympathy"],
    subcat: "keepsakes",
    price: "From $35",  // DRAFT PRICE — Lisa approval required
    desc: "A rotating selection of memorial plaques with cardinal and remembrance messages.",
    image: "lisa-037.webp",
    designType: "Plant or keepsake",
    coverageLabel: "Selection",
    coverageOptions: ["As photographed or closest current option"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Memorial Lantern",
    category: "gifts",
    collections: ["gifts", "sympathy"],
    subcat: "keepsakes",
    price: "From $45",  // DRAFT PRICE — Lisa approval required
    desc: "A white keepsake lantern with a comforting memorial verse.",
    image: "lisa-038.webp",
    designType: "Plant or keepsake",
    coverageLabel: "Selection",
    coverageOptions: ["As photographed or closest current option"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Friendship Keepsakes",
    category: "gifts",
    collections: ["gifts", "sympathy"],
    subcat: "keepsakes",
    price: "From $25",  // DRAFT PRICE — Lisa approval required
    desc: "Crosses, plaques and small friendship gifts; current wording and styles vary.",
    image: "lisa-039.webp",
    designType: "Plant or keepsake",
    coverageLabel: "Selection",
    coverageOptions: ["As photographed or closest current option"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Memorial Wind Chimes",
    category: "gifts",
    collections: ["gifts", "sympathy"],
    subcat: "keepsakes",
    price: 40,
    desc: "A memorial wind chime shown in detail and at full length.",
    image: "lisa-040.webp",
    photos: ["lisa-041.webp"],
    designType: "Plant or keepsake",
    coverageLabel: "Selection",
    coverageOptions: ["As photographed or closest current option"],
    draftNote: "This item's price was previously confirmed. The listing name and details shown here are drafts awaiting Lisa's review.",
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Greenery Casket Spray",
    category: "sympathy",
    subcat: "casket",
    price: 450,
    desc: "A full casket spray of layered greenery with natural texture and movement.",
    image: "lisa-064.webp",
    designType: "Casket spray",
    coverageLabel: "Casket coverage",
    coverageOptions: ["As photographed — confirm exact coverage"],
    order: "buy",
    buyLink: "",
  },
  {
    name: "Ladybug Dish Garden",
    category: "gifts",
    collections: ["gifts", "sympathy"],
    subcat: "keepsakes",
    price: "From $55",  // DRAFT PRICE — Lisa approval required
    desc: "A playful mixed dish garden with a ladybug accent.",
    image: "lisa-079.webp",
    designType: "Plant or keepsake",
    coverageLabel: "Selection",
    coverageOptions: ["As photographed or closest current option"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Faith Dish Garden",
    category: "gifts",
    collections: ["gifts", "sympathy"],
    subcat: "keepsakes",
    price: "From $55",  // DRAFT PRICE — Lisa approval required
    desc: "Mixed living plants with a cross and faith-inspired keepsake details.",
    image: "lisa-080.webp",
    designType: "Plant or keepsake",
    coverageLabel: "Selection",
    coverageOptions: ["As photographed or closest current option"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Classic Dish Garden",
    category: "gifts",
    collections: ["gifts", "sympathy"],
    subcat: "keepsakes",
    price: "From $55",  // DRAFT PRICE — Lisa approval required
    desc: "A generous bowl of mixed tropical plants for a lasting gift.",
    image: "lisa-088.webp",
    designType: "Plant or keepsake",
    coverageLabel: "Selection",
    coverageOptions: ["As photographed or closest current option"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  // ——— Wedding, prom & personal flowers ———
  {
    name: "Dusty Rose Corsage",
    category: "wedding",
    price: "From $35",  // DRAFT PRICE — Lisa approval required
    desc: "A dusty rose wrist corsage with purple and white accents.",
    image: "lisa-016.webp",
    designType: "Wedding or personal flowers",
    coverageLabel: "Design request",
    coverageOptions: ["Use the photographed design as direction", "Coordinate with my colors"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Peaceful White Lily Vase",
    category: "everyday",
    price: "From $125",  // DRAFT PRICE — Lisa approval required
    desc: "White lilies and roses arranged with eucalyptus and delicate accents in a matte black vase.",
    image: "lisa-017.webp",
    designType: "Fresh flower arrangement",
    coverageLabel: "Design size",
    coverageOptions: ["As photographed", "Smaller interpretation", "Fuller interpretation"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Blush Tulip Corsage",
    category: "wedding",
    price: "From $35",  // DRAFT PRICE — Lisa approval required
    desc: "A blush tulip wrist corsage finished with airy ribbon and pearl detail.",
    image: "lisa-030.webp",
    photos: ["lisa-031.webp"],
    designType: "Wedding or personal flowers",
    coverageLabel: "Design request",
    coverageOptions: ["Use the photographed design as direction", "Coordinate with my colors"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Blush Tulip Boutonniere",
    category: "wedding",
    price: "From $20",  // DRAFT PRICE — Lisa approval required
    desc: "A blush tulip boutonniere with clean greenery and a wrapped stem.",
    image: "lisa-032.webp",
    designType: "Wedding or personal flowers",
    coverageLabel: "Design request",
    coverageOptions: ["Use the photographed design as direction", "Coordinate with my colors"],
    draft: true,
    order: "buy",
    buyLink: "",
  },
  {
    name: "Pink Rose Boutonniere",
    category: "wedding",
    price: "From $20",  // DRAFT PRICE — Lisa approval required
    desc: "A soft pink rose boutonniere with white accents and textural greenery.",
    image: "lisa-033.webp",
    designType: "Wedding or personal flowers",
    coverageLabel: "Design request",
    coverageOptions: ["Use the photographed design as direction", "Coordinate with my colors"],
    draft: true,
    order: "buy",
    buyLink: "",
  },

  // ——— Retained existing listings ———
  {
    name: "Custom Arrangement",
    category: "everyday",
    price: "From $50",
    desc: "Tell us the occasion, color direction, and budget — we'll create a one-of-a-kind arrangement with the freshest flowers in the shop that day.",
    flowers: ["A seasonal mix of roses, carnations, accent flowers, and fresh greenery"],
    image: "",
    order: "custom",
    buyLink: "",
  },
  {
    name: "Holiday Centerpiece",
    category: "everyday",
    price: 55,
    desc: "Seasonal greens, candles, and fresh blooms for your table.",
    flowers: [],
    image: "",
    order: "buy",
    buyLink: "",
  },
  {
    name: "Fruit Basket",
    category: "gifts",
    price: "From $125",
    desc: "A generous basket of fresh fruit and goodies, customized to the recipient's tastes — and we happily work around any allergies.",
    flowers: [],
    image: "",
    order: "custom",
    buyLink: "",
  },
  {
    name: "Coffee Basket",
    category: "gifts",
    price: "From $100",
    desc: "For the coffee lover — brews, treats, and cozy extras, put together just for them.",
    flowers: [],
    image: "",
    order: "custom",
    buyLink: "",
  },
  {
    name: "Candy Basket",
    category: "gifts",
    price: "From $75",
    desc: "Sweets galore, customized to what they love — allergies happily accommodated.",
    flowers: [],
    image: "",
    order: "custom",
    buyLink: "",
  },
  {
    name: "Stuffed Animals",
    category: "gifts",
    price: "From $15",
    desc: "Stuffed animals from $15, with sizes, colors, and styles varying according to what is currently in stock — sweet on their own or added to an arrangement. Request current options and a member of our team will confirm the available selection and price.",
    flowers: [],
    image: "grey-brown-bears-2026.webp",
    photos: ["stuffed-animals-full-shelf-2026.webp", "stuffed-bears-shelf-2026.webp", "valentine-bears-three-2026.webp"],
    galleryKind: "inventory",
    order: "custom",
    buyLink: "",
  },
  {
    name: "Vase Collection",
    category: "gifts",
    price: "Varies",
    desc: "From bud vases to statement pieces, we match the vase to the size and style of your arrangement. Keepsake and premium styles available — just ask.",
    flowers: [],
    image: "",
    order: "custom",
    buyLink: "",
  },
  {
    name: "Wedding Flowers & Floral Design",
    category: "wedding",
    price: "Bouquets from $125 · packages by consultation",
    desc: "From the bridal bouquet and wedding-party flowers to ceremony pieces, sweetheart-table installations, and reception centerpieces, we can design a coordinated floral story around your colors, season, venue, and budget.",
    flowers: ["Bridal and attendant bouquets", "Boutonnieres and corsages", "Ceremony arrangements", "Sweetheart-table and reception flowers", "Centerpieces and finishing floral details"],
    image: "wedding-floral-installation.webp",
    photos: ["bridal-bouquet.jpg", "full-wedding-package.jpg", "wedding-table-centerpiece.webp", "wedding-ring-detail.webp"],
    order: "custom",
    buyLink: "",
    notice: "Wedding orders are custom, made over the phone — please order about 1 month ahead. A 50% deposit holds your date, with the balance due 2 weeks before the ceremony. Exceptions possible depending on the size of the order — just ask!",
    colors: ["Blush & ivory", "All white", "Bright & bold", "Your wedding colors"],
  },
];

/* ------------------------------------------------------------
   ADD-ONS — shown on every product's detail page and order popup.
     name         — what it is
     price        — what it costs
     amount       — exact numeric cart price, or null when the shop must confirm it
     requestOnly  — true keeps the item out of the paid subtotal and records it as a request
     customizable — true adds a small "can be customized" note
     note         — optional inventory or selection guidance
   ------------------------------------------------------------ */
const ADDONS = [
  { name: "Hand-written card message", price: "Free", amount: 0, customizable: true },
  { name: "Full Size Specialty Card", price: "$3", amount: 3, customizable: false, optionLabel: "Occasion", options: ["Birthday", "Sympathy", "Other"] },
  { name: "Personalized ribbon (your colors & wording)", price: "$5 per ribbon", amount: 5, customizable: true },
  { name: "Stuffed animal", price: "From $15", amount: null, requestOnly: true, customizable: false, note: "Selection and price vary with current shop inventory." },
  { name: "Memorial keepsake (cross, plaque, lantern)", price: "From $8", amount: null, requestOnly: true, customizable: true, note: "Our team will confirm the available keepsake and final price." },
  { name: "Latex balloon — shop supplied, helium included", price: "$2 each", amount: 2, customizable: false },
  { name: "Latex balloon inflation — customer supplied", price: "$1 each", amount: 1, customizable: false },
  { name: "Mylar balloon — shop supplied, helium included", price: "$5 each", amount: 5, customizable: false },
  { name: "Mylar balloon inflation — customer supplied", price: "$2 each", amount: 2, customizable: false },
  { name: "Upgraded keepsake vase", price: "Ask us", amount: null, requestOnly: true, customizable: true, note: "Style and price depend on current inventory." },
];

// Shown wherever add-ons appear — the promise that a real person confirms
// the details before anything gets made.
const ADDON_PROMISE =
  "Our selection of stuffed animals, keepsakes, and ribbon colors changes with what's in the " +
  "shop, and most can be customized to what you have in mind. Any order with add-ons " +
  "gets a quick follow-up call from us to confirm every detail — colors, wording, " +
  "sizing — so what arrives is exactly what you pictured.";

/* ------------------------------------------------------------
   SEASONS — automatic holiday pricing & banners.

   Dates are "MM-DD" and turn themselves ON and OFF every year, so you
   never have to remember to change holiday prices back afterward.

   prices:  override a product's price during the season. For a product
            with sizes, use { "Size Label": price }.
   banner:  message shown at the top of every page during the season.
   enabled: set false to switch a season off without deleting it.
   ------------------------------------------------------------ */
const SEASONS = [
  {
    name: "Valentine's Day",
    start: "02-01",
    end: "02-15",
    enabled: true,
    banner: "Valentine's Day orders are open — roses go fast, so call early!",
    prices: {},
  },
  {
    name: "Mother's Day",
    start: "05-01",
    end: "05-12",
    enabled: true,
    banner: "Mother's Day is coming — order early so we can get her the best blooms.",
    prices: {},
  },
  {
    name: "Prom Season",
    start: "03-15",
    end: "05-15",
    enabled: true,
    banner: "Prom season is here — bring us a photo of the dress and we'll match it.",
    prices: {},
  },
  {
    name: "Christmas",
    start: "11-25",
    end: "12-25",
    enabled: true,
    banner: "Christmas centerpieces and wreaths — order early for the holidays.",
    prices: {},
  },
];

/* ------------------------------------------------------------
   GALLERY — the "Our Work" page.
   ------------------------------------------------------------ */
const GALLERY = [
  { image: "garden-romance.jpg", caption: "Garden-style roses, hydrangea and snapdragons in soft pink", tag: "Everyday" },
  { image: "sunshine-morning.jpg", caption: "Yellow roses and gladiolus arranged for a bright East Texas morning", tag: "Everyday" },
  { image: "birthday-blooms.jpg", caption: "Peach roses, button mums and bright birthday color", tag: "Everyday" },
  { image: "get-well-soon.jpg", caption: "Cheerful gerbera daisies, roses and hydrangea", tag: "Everyday" },
  { image: "designers-choice.jpg", caption: "A garden mix designed from the freshest flowers in the shop", tag: "Everyday" },
  { image: "rose-bouquet.jpg", caption: "Classic long-stem roses with baby's breath and greenery", tag: "Everyday" },
  { image: "gallery-01.jpg", caption: "Golden roses, white callas and blue delphinium casket spray", tag: "Sympathy" },
  { image: "gallery-02.jpg", caption: "All-white casket spray with a well-worn cowboy hat", tag: "Sympathy" },
  { image: "gallery-03.jpg", caption: "Red roses and blue delphinium with Texas flags", tag: "Sympathy" },
  { image: "gallery-04.jpg", caption: "Lilies and antique-pink roses in soft lavender tones", tag: "Sympathy" },
  { image: "gallery-05.jpg", caption: "A heart of golden roses edged in blue", tag: "Sympathy" },
  { image: "gallery-06.jpg", caption: "Autumn lilies, roses and tulips in full color", tag: "Sympathy" },
  { image: "gallery-07.jpg", caption: "White lilies, hydrangea and roses with curly willow", tag: "Everyday" },
  { image: "gallery-08.jpg", caption: "Yellow roses rising through blue and white", tag: "Sympathy" },
  { image: "gallery-09.jpg", caption: "Pink lilies and roses with deep purple stock", tag: "Everyday" },
  { image: "gallery-10.jpg", caption: "White carnation heart with a spray of pink roses", tag: "Sympathy" },
  { image: "gallery-11.jpg", caption: "Blush tulip corsage with pearls and ribbon", tag: "Prom & Seasonal" },
  { image: "gallery-12.jpg", caption: "Spring bouquet with a balloon bunch", tag: "Everyday" },
  { image: "gallery-13.jpg", caption: "Snowy lilies and glads with deep red carnations", tag: "Sympathy" },
  { image: "gallery-14.jpg", caption: "Ivory roses and callas cascading with soft greens", tag: "Sympathy" },
  { image: "gallery-15.jpg", caption: "Cemetery vase flowers in lasting silk", tag: "Silk & Cemetery" },
  { image: "peaceful-garden-basket.jpg", caption: "Yellow roses and blue delphinium gathered in a garden basket", tag: "Sympathy" },
  { image: "bridal-bouquet.jpg", caption: "Hand-tied bridal bouquet in blush, blue and soft greenery", tag: "Weddings" },
  { image: "full-wedding-package.jpg", caption: "Coordinated wedding flowers designed around the couple's colors", tag: "Weddings" },
  { image: "wedding-floral-installation.webp", caption: "Ivory and blush reception flowers designed across the sweetheart table and floor arrangements", tag: "Weddings" },
  { image: "wedding-table-centerpiece.webp", caption: "Candlelit reception table flowers with roses, baby's breath and fresh greenery", tag: "Weddings" },
  { image: "wedding-ring-detail.webp", caption: "Wedding rings framed with ivory and peach roses for a thoughtful finishing detail", tag: "Weddings" },
  { image: "prom-homecoming.jpg", caption: "Blush tulip corsage finished with ribbon and pearl details", tag: "Prom & Seasonal" },
  { image: "plants-dish-gardens.jpg", caption: "Layered green dish garden with easy-care plants", tag: "Plants & Gifts" },
  { image: "plants-dish-gardens-2.jpg", caption: "A second garden of living greens for a lasting gift", tag: "Plants & Gifts" },
  { image: "vase-collection.jpg", caption: "Keepsake vases ready to shape a custom arrangement", tag: "Plants & Gifts" },
  { image: "cemetery-subscription.jpg", caption: "Lasting cemetery flowers prepared for thoughtful placement", tag: "Silk & Cemetery" },
  { image: "golden-tulip-garden.webp", caption: "Golden tulips in a modern garden-style vase", tag: "Everyday" },
  { image: "purple-birthday-basket.webp", caption: "Purple and green birthday flowers gathered in a basket", tag: "Everyday" },
  { image: "gerbera-garden-vase.webp", caption: "Gerbera daisies and roses in a bright garden mix", tag: "Everyday" },
  { image: "birthday-balloon-flowers.webp", caption: "Birthday flowers finished with a cheerful balloon", tag: "Everyday" },
  { image: "blush-garden-vase.webp", caption: "Blush roses and garden textures in soft color", tag: "Everyday" },
  { image: "jewel-tone-vase.webp", caption: "A jewel-tone vase arrangement designed from the workroom", tag: "Everyday" },
  { image: "white-lily-vase.webp", caption: "White lilies arranged with fresh green texture", tag: "Everyday" },
  { image: "pink-rose-vase-2026.webp", caption: "Pink roses and waxflower in a classic glass vase", tag: "Everyday" },
  { image: "vibrant-rose-cube-2026.webp", caption: "Coral and hot-pink roses with carnations in a modern cube vase", tag: "Everyday" },
  { image: "yellow-pink-everyday-vase-2026.webp", caption: "Yellow roses and calla lilies with pink lilies, green hydrangea, and rich seasonal color", tag: "Everyday" },
  { image: "pink-lily-casket-spray-2026.webp", caption: "A lavish pink casket spray with roses, lilies, carnations, stock, and garden textures", tag: "Sympathy" },
  { image: "sympathy-casket-pink.webp", caption: "A full pink casket spray designed with tenderness", tag: "Sympathy" },
  { image: "sympathy-casket-yellow.webp", caption: "Golden and white flowers arranged as a casket tribute", tag: "Sympathy" },
  { image: "sympathy-sunflower-tribute.webp", caption: "Sunflowers and vivid color in a personal memorial tribute", tag: "Sympathy" },
  { image: "sympathy-sunflower-standing-2024.webp", caption: "A tall sunflower easel spray with blue accents", tag: "Sympathy" },
  { image: "sympathy-wreath-pink.webp", caption: "A soft pink memorial wreath with garden flowers", tag: "Sympathy" },
  { image: "patriotic-memorial-spray.webp", caption: "A red, white and blue tribute honoring a life of service", tag: "Sympathy" },
  { image: "white-blue-casket-spray.webp", caption: "White and blue casket flowers with quiet, tailored detail", tag: "Sympathy" },
  { image: "cowboy-casket-spray.webp", caption: "A white casket spray designed around a treasured cowboy hat", tag: "Sympathy" },
  { image: "white-cascade-spray.webp", caption: "White lilies and roses in a graceful cascading tribute", tag: "Sympathy" },
  { image: "blue-yellow-silk-cemetery.webp", caption: "Blue and yellow silk cemetery flowers treated for the weather", tag: "Silk & Cemetery" },
  { image: "blue-yellow-silk-cemetery-2.webp", caption: "A second lasting cemetery design in blue and yellow", tag: "Silk & Cemetery" },
  { image: "dusty-rose-corsage.webp", caption: "A dusty rose corsage finished with delicate detail", tag: "Prom & Seasonal" },
  { image: "white-lily-boutonniere.webp", caption: "A white lily boutonniere with clean greenery", tag: "Prom & Seasonal" },
  { image: "ladybug-dish-garden.webp", caption: "A playful dish garden with easy-care plants and a ladybug accent", tag: "Plants & Gifts" },
  { image: "peace-lily-memorial-garden.webp", caption: "A peaceful green plant garden made as a lasting remembrance", tag: "Plants & Gifts" },
  { image: "mixed-plant-basket.webp", caption: "A full basket of mixed living plants", tag: "Plants & Gifts" },
  { image: "classic-bears-three-2026.webp", caption: "A rotating selection of stuffed bears available as gifts or arrangement add-ons", tag: "Plants & Gifts" },
];
